steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 
           'asia-south1-docker.pkg.dev/$PROJECT_ID/vaayumitra/app:$COMMIT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 
           'asia-south1-docker.pkg.dev/$PROJECT_ID/vaayumitra/app:$COMMIT_SHA']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - vaayumitra
      - '--image=asia-south1-docker.pkg.dev/$PROJECT_ID/vaayumitra/app:$COMMIT_SHA'
      - '--region=asia-south1'
      - '--allow-unauthenticated'
      - '--min-instances=1'
      - '--memory=1Gi'
      - '--port=8080'
